# Generated by Django 4.2.17 on 2026-02-07 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('timeout', 'Таймаут')], db_index=True, max_length=20)),
                ('error_summary', models.TextField(blank=True)),
                ('response_time_ms', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('prec_type', models.IntegerField(blank=True, null=True)),
                ('prec_strength', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.IntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude', '-fetched_at'], name='weather_app_latitud_c3a4b1_idx'), models.Index(fields=['-fetched_at'], name='weather_app_fetched_3ad965_idx')],
            },
        ),
    ]
