# Generated by Django 4.2.17 on 2026-02-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='timezone_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weatherfetchlog',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['timezone_name'], name='weather_app_timezon_629723_idx'),
        ),
    ]
